# Generated by Django 3.2.7 on 2021-09-25 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='courses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_id', models.CharField(max_length=20)),
                ('course_name', models.CharField(max_length=50)),
                ('slot', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'courses',
            },
        ),
        migrations.CreateModel(
            name='slot_time_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(max_length=20)),
                ('hour1', models.CharField(max_length=50)),
                ('hour2', models.CharField(max_length=50)),
                ('hour3', models.CharField(max_length=50)),
                ('hour4', models.CharField(max_length=50)),
                ('hour5', models.CharField(max_length=50)),
                ('hour6', models.CharField(max_length=50)),
                ('hour7', models.CharField(max_length=50)),
                ('hour8', models.CharField(max_length=50)),
                ('hour9', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'slot_time_table',
            },
        ),
        migrations.CreateModel(
            name='students',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(max_length=20)),
                ('course_id', models.CharField(max_length=20)),
                ('batch_id', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'student',
            },
        ),
        migrations.CreateModel(
            name='teachers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teacher_id', models.CharField(max_length=20)),
                ('course_id', models.CharField(max_length=20)),
                ('batch_id', models.CharField(max_length=20)),
                ('cr_id', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'teacher',
            },
        ),
        migrations.CreateModel(
            name='time_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_id', models.CharField(max_length=20)),
                ('batch_id', models.CharField(max_length=20)),
                ('allocation', models.CharField(max_length=1000)),
            ],
            options={
                'db_table': 'time_table',
            },
        ),
    ]
