# Generated by Django 3.2.7 on 2021-09-25 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MDAT', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teachers',
            name='cr_id',
        ),
    ]
