# Generated by Django 3.2.7 on 2021-09-25 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MDAT', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teachers',
            name='cr_id',
        ),
        migrations.AlterField(
            model_name='teachers',
            name='teacher_id',
            field=models.CharField(max_length=50),
        ),
    ]
