# Generated by Django 3.2.7 on 2021-09-25 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MDAT', '0002_remove_teachers_cr_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teachers',
            name='teacher_id',
            field=models.CharField(max_length=50),
        ),
    ]
